### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by usernotnull** [javisperez/tailwindcontentplaceholder#4]
I wish I can help more with debugging but this is too dark for me.
After I have updated my npm dependencies, my tailwind build started to fail with the following:

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
URIError: URI malformed
 at decodeURI (<anonymous>)
    at normalizeUrl
```

Here is my minimalist config for testing:
```
        require('tailwind-content-placeholder')({
            placeholders: {
                'list': {
                    height: 4,
                    rows: [
                        [20, 80],
                        [20, 60]
                    ]
                },
            }
        }),

```

Removing the above require solves the issue, but I'm not sure what caused it from this lib.
Removing the (@import "tailwindcss/components";) from my app.scss also solves the issue too, so it's something injected by this lib into tailwind css in my scss file.

**Comment by javisperez** [comment]
Oh, weird... i'll be taking a look soon-ish. Thanks for the issue.

**Comment by zygopleural** [comment]
Have you managed to look into it yet? 🙃

**Comment by javisperez** [comment]
hey guys sorry again for the delay, have been super busy, and given that I couldn't reproduce this, it was kinda tricky to even figure what could be the possible root cause. Thanks to @ollieRogers for the fix PR, I've just merged it, will be releasing it asap.

**Comment by usernotnull** [comment]
Unfortunately, this was dropped from the project which was failing so I have no way to test this.
I'll close this issue because the merge should resolve this in theory.

Anyone who faces this issue again after the new release can reopen this issue.
